config/routes.rb
Opentok::Application.routes.draw do
  devise_for :users

  resource :rooms
  match '/party/:id', :to => "rooms#party", :as => :party, :via => :get
  resources :users do 
    member do
      get :find_ticket
      get :auth
    end
  end

  root :to => 'rooms#index'

end

app/models/room.rb
class Room
  include Mongoid::Document
  field :name, type: String
  field :session_Id, type: String
  field :public, type: Boolean
  field :timestamp, type: DateTime

end

app/models/user.rb
class User
  include Mongoid::Document
  include BoxHelper

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String
  field :ticket, :type => String, :default => "nothing"
  field :auth, :type => String


  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index

    @rooms = Room.where(:public => true).order_by([:timestamp,:desc])
    @new_room = Room.new


  end

  def create
    config_opentok
    session = @opentok.create_session request.remote_addr
    params[:room][:sessionId] = session.session_id

    @new_room = Room.new(params[:room])

    respond_to do |format|
      if @new_room.save
        format.html { redirect_to("/party/"+@new_room.id.to_s) }
      else
        format.html { render :controller => 'rooms', :action => "index" }
      end
    end
  end

  def party
    @room = Room.find(params[:id])

    config_opentok

    @tok_token = @opentok.generate_token :session_id => @room.sessionId
  end

  private
  def config_opentok
    if @opentok.nil?
      	@opentok = OpenTok::OpenTokSDK.new 17075832, "064b64e0f5c46629e209882a8cee6d63124a3619"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include BoxHelper

  before_filter :authenticate_user!

  def show
  	@user = User.find(params[:id])

  end

  def find_ticket
  	@user = User.find(params[:id])
    get_ticket(@user)
    redirect_to user_path(@user)

  end

  def auth
  	@user = User.find(params[:id])
  	verify_auth(@user)
  	redirect_to user_path(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/box_helper.rb
module BoxHelper

require 'net/http'
require 'net/https'
require "uri"


  def get_ticket(user)
  	uri = URI.parse(URI.encode("https://www.box.com/api/1.0/rest?action=get_ticket&api_key=x0dcfl3a1vjc56j0sg6cytjfm3dt5r05"))
  	http = Net::HTTP.new(uri.host, uri.port)
  	http.use_ssl = true
	http.verify_mode = OpenSSL::SSL::VERIFY_NONE
	response = http.request(Net::HTTP::Get.new(uri.request_uri))
	@doc = Nokogiri::XML(response.body)
	@response=@doc.xpath("/response/ticket").first.content
	user.update_attributes(ticket: @response)
	return @response
  end

  def verify_auth(user)
  	@ticket=user.ticket
  	uri = URI.parse(URI.encode("https://www.box.com/api/1.0/rest?action=get_auth_token&api_key=x0dcfl3a1vjc56j0sg6cytjfm3dt5r05&ticket=#{@ticket}"))
  	http = Net::HTTP.new(uri.host, uri.port)
  	http.use_ssl = true
	http.verify_mode = OpenSSL::SSL::VERIFY_NONE
	response = http.request(Net::HTTP::Get.new(uri.request_uri))
	@doc = Nokogiri::XML(response.body)
	@response=@doc.xpath("/response/auth_token").first.content
	user.update_attributes(auth: @response)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Opentok</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/rooms/_newform.html.erb
Start a new party room
<%= form_for(@new_room) do |f| %>
	Party Name: <%= f.text_field :name %><br/><br/>
	Public? <%= f.check_box :public %><br/><br/>
<%= f.submit %>
<% end %>

app/views/rooms/index.html.erb
index.html.erb

<%= render 'rooms/newform' %>

	<% @rooms.each do |room| %>
		<a href="/party/<%= room.id %>"><%= room.name %></a>
	<%end%>
new_rooms
 <%= link_to "new room", new_rooms_path, :method => :get%>
<%=link_to("Logout", destroy_user_session_path, :method => :delete)%>
  <%= link_to('Login', new_user_session_path)  %>  

 <%= link_to "registration", new_user_registration_path %>

<% if user_signed_in? %><%= link_to "Auth", user_path(current_user) %> <%end%>

app/views/rooms/new.html.erb
new.html.erb
<% form_for(@new_room) do |f| %>
	Party Name: <%= f.text_field :name %><br/><br/>
	Public? <%= f.check_box :public %><br/><br/>

	<%= f.submit %>
<% end %>

app/views/rooms/party.html.erb
<div id="videobox">
	
</div>
<script src="http://static.opentok.com/v0.91/js/TB.min.js" type="text/javascript"></script>
<script type="text/javascript">
	var apiKey = 17075832; 
	var sessionId = "<%= @room.sessionId %>"; 
	var token = "<%= @tok_token %>"; 

	var session;

	TB.addEventListener('exception', exceptionHandler);
	session = TB.initSession(sessionId);

	//Video chat event listeners
	session.addEventListener('sessionConnected', sessionConnectedHandler);
	session.addEventListener('streamCreated', streamCreatedHandler);
    session.addEventListener('streamDestroyed', streamDestroyedHandler);

	session.connect(apiKey, token);
</script>

app/views/users/show.html.erb
show.html.erb
ticket <%= @user.ticket %>
auth <%= @user.auth %>
<%= link_to "Find ticket", find_ticket_user_path(@user) %>
<%= link_to "Login on box", "https://www.box.com/api/1.0/auth/#{@user.ticket}",:target => '_blank' %>
<%= link_to "Auth", auth_user_path(@user) %> 	